a

diff --git a/glados b/glados
--- a/glados
+++ b/glados
@@ -86,7 +86,7 @@ function ask_bai() {
 #-----------------------ARGS CHECKER-----------------------
 ARGS=$(getopt -o rcnhvuso --long uninstall,settings -n "$0" -- "$@" 2>/dev/null)
 if [ $? -ne 0 ] && [ "$1" != "--flags" ]; then
-	printf "\n${red}Command Not Found!\n${blue}Use '-h' to get more help\n"
+	printf "\n${red}'$?' - Command Not Found!\n${blue}Use '-h' to get more help\n"
 	stty echo
 	exit
 fi
